name: Tim Mansfield
favicon: null
layout_spectrum: 0.00437
typography_spectrum: 0.2405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232429'
    - '#6a6a68'
    - '#669957'
    - '#3a513d'
    - '#b3c59f'
  brandStrength: 0.8125
  lightness: 0.5803753093350679
  saturation: 0.6502202041447163
  rhythmicContrast: 0.25
purpose: []
